[package]
name = "string-collect"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector", "Alexey Galakhov", "Daniel Abramov", "Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/stackinspector/string-collect"

[lib]
path = "lib.rs"
